warning( "This file has been generated by Monkey Studio (2006.1.6.0) - http://sourceforge.net/projects/monkeystudio" )

include( ../../plugins.inc )

TEMPLATE	= lib
LANGUAGE	= C++
CONFIG	+= warn_on release lib_bundle thread x11 dll plugin
DESTDIR	= $$MONKEY_PLUGINS_DIR/workspace
RESOURCES	= src/resources/messagebox_resources.qrc

SOURCES	= src/MessageBox.cpp \
	src/ui/UIMessageBox.cpp

FORMS	= src/ui/UIMessageBox.ui

HEADERS	= src/MessageBox.h \
	src/ui/UIMessageBox.h

