warning( "This file has been generated by Monkey Studio (2006.1.6.0) - http://sourceforge.net/projects/monkeystudio" )

include( ../../plugins.inc )

QT += core gui
TEMPLATE	= lib
LANGUAGE	= C++
CONFIG	+= warn_on debug lib_bundle thread x11 dll plugin
DESTDIR	= $$MONKEY_PLUGINS_DIR/workspace
INCLUDEPATH += ../../../monkey/src/ctags
INCLUDEPATH += ../../../monkey/src/3rdparty/exuberantCtags
#RESOURCES	= resources/classbrouser_resources.qrc

SOURCES	= ClassBrouser.cpp  \
		Entity.cpp  \
		EntityContainer.cpp 
#		ClassBrouserSettings.cpp
		

HEADERS	= ClassBrouser.h	\
		Entity.h  \
		EntityContainer.h 
#		ClassBrouserSettings.h


