warning( "This file has been generated by Monkey Studio (2006.1.6.0) - http://sourceforge.net/projects/monkeystudio" )

OBJECTS_DIR	= build/.obj

UI_DIR	= build/.ui

LAST_EXE_TYPE	= release
RCC_DIR	= build/.rcc

MOC_DIR	= build/.moc

TEMPLATE	= app
QT	= gui core
LANGUAGE	= C++
INCLUDEPATH	= . src src/forms src/3rdparty/parser src/3rdparty/parser/forms src/ui/
CONFIG	+= qt warn_on debug thread windows console
RESOURCES	= src/3rdparty/parser/resources/resources.qrc src/3rdparty/parser/resources/resources2.qrc

SOURCES	= src/3rdparty/parser/ProjectItem.cpp \
	src/3rdparty/parser/ProjectItemModel.cpp \
	src/3rdparty/parser/ProjectProxyModel.cpp \
	src/main.cpp \
	src/ProjectSettingsProxyModel.cpp \
	src/ui/UIProjectSettingsProxyModel.cpp \
	src/ui/UIProjectsViewer.cpp \
	src/ui/UIItemSettings.cpp \
	src/ProjectItemDelegate.cpp

FORMS	= src/ui/UIProjectSettingsProxyModel.ui \
	src/ui/UIProjectsViewer.ui \
	src/ui/UIItemSettings.ui

OPENEDFILES	= src/3rdparty/parser/ProjectItem.h \
	src/3rdparty/parser/ProjectItem.cpp \
	src/3rdparty/parser/ProjectItemModel.h \
	src/3rdparty/parser/ProjectItemModel.cpp \
	src/3rdparty/parser/ProjectProxyModel.h \
	src/3rdparty/parser/ProjectProxyModel.cpp \
	src/ui/UIProjectSettingsProxyModel.h \
	src/ui/UIProjectSettingsProxyModel.cpp

HEADERS	= src/3rdparty/parser/ProjectItem.h \
	src/3rdparty/parser/ProjectItemModel.h \
	src/3rdparty/parser/ProjectProxyModel.h \
	src/ProjectSettingsProxyModel.h \
	src/ui/UIProjectSettingsProxyModel.h \
	src/ui/UIProjectsViewer.h \
	src/ui/UIItemSettings.h \
	src/ProjectItemDelegate.h

