######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 8 16:13:40 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += asdf.h
SOURCES += asdf.cpp main.cpp
RESOURCES += resources.qrc
