######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 8 22:06:55 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += asdf.h
SOURCES += asdf.cpp main.cpp
RESOURCES += resources.qrc
