warning( "This file has been generated by Monkey Studio (2006.1.6.0) - http://sourceforge.net/projects/monkeystudio" )

unix:OBJECTS_DIR	= build/.o/unix
win32:OBJECTS_DIR	= build/.o/win32
mac:OBJECTS_DIR	= build/.o/mac
UI_DIR	= build/.ui
MOC_DIR	= build/.moc
RCC_DIR	= build/.rcc

TEMPLATE	= app
LIBS	= -lqscintilla2
QT	= gui core
LANGUAGE	= C++
INCLUDEPATH	= . src src/ui src/3rdparty/objects/pSettings src/3rdparty/widgets/pMenuBar src/3rdparty/widgets/pTabWorkspace src/maininterface/ui src/maininterface src/menutools/ src/workspace/ src/projectmanager/ src/editor/ src/menutools/ui/
CONFIG	+= qt warn_on debug app_bundle thread x11 windows
RESOURCES	= src/resources/resources.qrc

SOURCES	= src/3rdparty/objects/pSettings/pSettings.cpp \
	src/3rdparty/widgets/pMenuBar/pMenuBar.cpp \
	src/3rdparty/widgets/pTabWorkspace/pTabWorkspace.cpp \
	src/3rdparty/widgets/pTabWorkspace/pRightCorner.cpp \
	src/maininterface/Settings.cpp \
	src/maininterface/MenuBar.cpp \
	src/menutools/MenuTools.cpp \
	src/maininterface/StatusBar.cpp \
	src/menutools/ui/UIToolsEdit.cpp \
	src/maininterface/ui/UITranslator.cpp \
	src/maininterface/ui/UIAbout.cpp \
	src/maininterface/ui/UIMain.cpp \
	src/workspace/Workspace.cpp \
	src/projectmanager/ProjectManager.cpp \
	src/editor/MonkeyEditor.cpp \
	src/Monkey.cpp \
	src/main.cpp

FORMS	= src/maininterface/ui/UIMain.ui \
	src/maininterface/ui/UITranslator.ui \
	src/menutools/ui/UIToolsEdit.ui \
	src/maininterface/ui/UIAbout.ui

OPENEDFILES	= src/maininterface/Settings.h \
	src/maininterface/Settings.cpp \
	src/maininterface/MenuBar.h \
	src/maininterface/MenuBar.cpp \
	src/menutools/MenuTools.h \
	src/menutools/MenuTools.cpp \
	src/maininterface/ui/UIMain.h \
	src/maininterface/ui/UIMain.cpp \
	src/Monkey.h \
	src/Monkey.cpp \
	src/workspace/Workspace.h \
	src/workspace/Workspace.cpp \
	src/projectmanager/ProjectManager.h \
	src/projectmanager/ProjectManager.cpp \
	src/3rdparty/widgets/pMenuBar/pMenuBar.h \
	src/3rdparty/widgets/pMenuBar/pMenuBar.cpp \
	src/maininterface/ui/UIAbout.h \
	src/maininterface/ui/UIAbout.cpp \
	ToDo.txt \
	src/maininterface/StatusBar.h \
	src/maininterface/StatusBar.cpp \
	src/editor/MonkeyEditor.h \
	src/editor/MonkeyEditor.cpp \
	src/main.h \
	src/main.cpp

HEADERS	= src/3rdparty/objects/pSettings/pSettings.h \
	src/3rdparty/widgets/pMenuBar/pMenuBar.h \
	src/3rdparty/widgets/pTabWorkspace/pTabWorkspace.h \
	src/3rdparty/widgets/pTabWorkspace/pRightCorner.h \
	src/maininterface/Settings.h \
	src/maininterface/MenuBar.h \
	src/menutools/MenuTools.h \
	src/maininterface/StatusBar.h \
	src/menutools/ui/UIToolsEdit.h \
	src/maininterface/ui/UITranslator.h \
	src/maininterface/ui/UIAbout.h \
	src/maininterface/ui/UIMain.h \
	src/workspace/Workspace.h \
	src/projectmanager/ProjectManager.h \
	src/editor/MonkeyEditor.h \
	src/Monkey.h \
	src/main.h

