warning( "This file has been generated by Monkey Studio (2006.1.6.0) - http://sourceforge.net/projects/monkeystudio" )

include( src/3rdparty/qscintilla/qscintilla.inc )

unix:OBJECTS_DIR	= ../build/.o/unix/monkey
win32:OBJECTS_DIR	= ../build/.o/win32/monkey
mac:OBJECTS_DIR	= ../build/.o/mac/monkey
UI_DIR	= ../build/.ui
MOC_DIR	= ../build/.moc/monkey
RCC_DIR	= ../build/.rcc/monkey

unix:ICON	= src/resources/Icons/icon.png
mac:ICON	= src/resources/Icons/icon.icns
win32:ICON	= src/resources/Icons/icon.ico

TEMPLATE	= app
DEFINES	= MONKEY_CORE_BUILD #__COVERAGESCANNER__
LIBS	= -L../build/.lib -lqscintilla2
linux-g++:LIBS	+= -rdynamic
win32-msvc:LIBS	+= /IMPLIB:../build/.lib/monkey.lib
win32-g++:LIBS	+= -Wl,--out-implib,../build/.lib/libmonkey.a
QT	= gui core
LANGUAGE	= C++
INCLUDEPATH	= . src src/ui \
	src/3rdparty/objects/pSettings \
	src/3rdparty/widgets/pMenuBar \
	src/workspacemanager \
	src/maininterface \
	src/toolsmanager/ui \
	src/3rdparty/widgets/pTabToolBar \
	src/3rdparty/widgets/pTabWorkspace \
	src/projectsmanager/ui \
	src/projectsmanager \
	src/pluginsmanager \
	src/pluginsmanager/ui \
	src/maininterface/ui \
	src/toolsmanager \
	src/recentsmanager \
	src/monkeyeditor/ui \
	src/3rdparty/qscintilla/$$QSCINTILLAVERSION/Qt4/Qsci \
	src/3rdparty/qscintilla/$$QSCINTILLAVERSION/Qt4 \
	src/3rdparty/coveragemeter/ui

CONFIG	+= qt warn_on release app_bundle thread x11 windows console
DESTDIR	= ../bin
win32:RC_FILE	+= monkey.rc
RESOURCES	= src/resources/resources.qrc

contains( DEFINES, __COVERAGESCANNER__ ) {
	message( "Coverage Meter Activated ( http://www.coveragemeter.com )." )
	QMAKE_CXX = cs$$QMAKE_CXX
	QMAKE_LINK = cs$$QMAKE_LINK
	QMAKE_CC = cs$$QMAKE_CC
}

SOURCES	= src/3rdparty/objects/pSettings/pSettings.cpp \
	src/3rdparty/widgets/pMenuBar/pMenuBar.cpp \
	src/3rdparty/widgets/pTabWorkspace/pTabWorkspace.cpp \
	src/3rdparty/widgets/pTabWorkspace/pRightCorner.cpp \
	src/3rdparty/widgets/pTabToolBar/kmultitabbar.cpp \
	src/3rdparty/widgets/pTabToolBar/pTabToolBar.cpp \
	src/3rdparty/widgets/pTabToolBar/pTabToolBarManager.cpp \
	src/maininterface/Settings.cpp \
	src/maininterface/MenuBar.cpp \
	src/maininterface/StatusBar.cpp \
	src/maininterface/ui/UITranslator.cpp \
	src/recentsmanager/RecentsManager.cpp \
	src/toolsmanager/ToolsManager.cpp \
	src/toolsmanager/ui/UIToolsEdit.cpp \
	src/maininterface/ui/UIAbout.cpp \
	src/maininterface/ui/UIMain.cpp \
	src/monkeyeditor/ui/qscintillaSearch.cpp \
	src/monkeyeditor/MonkeyEditor.cpp \
	src/workspacemanager/UISaveFiles.cpp \
	src/workspacemanager/TabToolBar.cpp \
	src/workspacemanager/Workspace.cpp \
	src/workspacemanager/LeftCorner.cpp \
	src/pluginsmanager/PluginsManager.cpp \
	src/projectsmanager/AbstractProjectModel.cpp \
	src/projectsmanager/AbstractProjectProxy.cpp \
	src/projectsmanager/ui/ProjectsManager.cpp \
	src/Monkey.cpp \
	src/main.cpp \
	src/pluginsmanager/ui/UIPluginsSettings.cpp  \
	src/3rdparty/coveragemeter/ui/UITestReport.cpp \
	src/maininterface/ui/UISettings.cpp


FORMS	= src/maininterface/ui/UITranslator.ui \
	src/toolsmanager/ui/UIToolsEdit.ui \
	src/maininterface/ui/UIAbout.ui \
	src/maininterface/ui/UIMain.ui \
	src/monkeyeditor/ui/qscintillaSearch.ui \
	src/projectsmanager/ui/ProjectsManager.ui \
	src/pluginsmanager/ui/UIPluginsSettings.ui \
	src/3rdparty/coveragemeter/ui/UITestReport.ui \
	src/maininterface/ui/UISettings.ui

HEADERS	= src/3rdparty/objects/pSettings/pSettings.h \
	src/3rdparty/widgets/pMenuBar/pMenuBar.h \
	src/3rdparty/widgets/pTabWorkspace/pTabWorkspace.h \
	src/3rdparty/widgets/pTabWorkspace/pRightCorner.h \
	src/3rdparty/widgets/pTabToolBar/kmultitabbar.h \
	src/3rdparty/widgets/pTabToolBar/pTabToolBar.h \
	src/3rdparty/widgets/pTabToolBar/pTabToolBarManager.h \
	src/maininterface/Settings.h \
	src/maininterface/MenuBar.h \
	src/maininterface/StatusBar.h \
	src/maininterface/ui/UITranslator.h \
	src/recentsmanager/RecentsManager.h \
	src/toolsmanager/ToolsManager.h \
	src/toolsmanager/ui/UIToolsEdit.h \
	src/maininterface/ui/UIAbout.h \
	src/maininterface/ui/UIMain.h \
	src/monkeyeditor/ui/qscintillaSearch.h \
	src/monkeyeditor/MonkeyEditor.h \
	src/workspacemanager/AbstractChild.h \
	src/workspacemanager/UISaveFiles.h \
	src/workspacemanager/TabToolBar.h \
	src/workspacemanager/Workspace.h \
	src/workspacemanager/LeftCorner.h \
	src/pluginsmanager/MonkeyExport.h \
	src/pluginsmanager/BasePlugin.h \
	src/pluginsmanager/PluginsManager.h \
	src/pluginsmanager/WorkspacePlugin.h \
	src/pluginsmanager/ChildPlugin.h \
	src/pluginsmanager/CompilerPlugin.h \
	src/pluginsmanager/DebuggerPlugin.h \
	src/pluginsmanager/ProjectPlugin.h \
	src/projectsmanager/AbstractProjectModel.h \
	src/projectsmanager/AbstractProjectProxy.h \
	src/projectsmanager/ui/ProjectsManager.h \
	src/Monkey.h \
	src/main.h \
	src/pluginsmanager/ui/UIPluginsSettings.h \
	src/3rdparty/coveragemeter/ui/UITestReport.h \
	src/maininterface/ui/UISettings.h

