warning( "This file has been generated by Monkey Studio (2006.1.6.0) - http://sourceforge.net/projects/monkeystudio" )

TEMPLATE	= subdirs

SOURCES	= monkey/src/projectsmanager/AbstractProjectModel.cpp \
	monkey/src/projectsmanager/AbstractProjectProxy.cpp

SUBDIRS	= monkey/src/3rdparty/qscintilla \
	monkey \
	plugins

HEADERS	= monkey/src/projectsmanager/AbstractProjectModel.h \
	monkey/src/projectsmanager/AbstractProjectProxy.h

