warning( "This file has been generated by Monkey Studio (2006.1.6.0) - http://sourceforge.net/projects/monkeystudio" )

include( ../../plugins.inc )

TEMPLATE 	= lib
LANGUAGE	= C++
CONFIG	+= warn_on release lib_bundle thread x11 dll plugin
DESTDIR	= $$MONKEY_PLUGINS_DIR/workspace
RESOURCES	+= src/QFileBrowser.qrc
TARGET	= QFileBrowser

SOURCES	= $$SOURCES \
	src/QFileBrowser.cpp \
	src/QFileBrowserChild.cpp

HEADERS = $$HEADERS \
	src/QFileBrowser.h \
	src/QFileBrowserChild.h
